name: Dhyaa
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1
  fluttertoast: ^8.0.8
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.2
  provider: ^6.0.3
  shared_preferences:
  intl_phone_number_input: ^0.7.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.5
  get_storage:
  get:
  intl: any
  flutter_localization: ^0.1.9
  date_picker_timeline:
  sqflite:
  flutter_staggered_animations:
  custom_navigator:
    git:
      url: https://github.com/bradintheusa/Custom-navigator.git
  material_tag_editor: ^0.1.2
  moyasar_payment: ^0.1.4
  webview_flutter: ^3.0.4
  flutter_credit_card: ^3.0.4
  table_calendar: ^3.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
